### ISSUE TITLE
Values set as false disappear

### ISSUE THREAD

**Issue by alxgrepe** [dword-design/nuxt-route-meta#47]
When setting one of the metadata fields to false, they disappear completely from the $route.meta .

File test.vue:
```
<template>
<code>
isTrue: {{ this.$route.meta.isTrue }}
isFalse: {{ this.$route.meta.isFalse }}
isOther: {{ this.$route.meta.isOther }}
isAlsoTrue: {{ this.$route.meta.isAlsoTrue }}
isAlsoFalse: {{ this.$route.meta.isAlsoFalse }}
</code>
</template>

<script>
export default {
  isTrue: true,
  isFalse: false,
  isOther: 'other',
  meta: {
    isAlsoTrue: true,
    isAlsoFalse: false,
  },
}
</script>

<style scoped>
code {  white-space: pre-wrap; }
</style>
```

Output:
```
  isTrue: true
  isFalse: 
  isOther: other
  isAlsoTrue: true
  isAlsoFalse: 
```

(I'm using v2.0.6 and nuxt v2.15.3.)
